version: "3"
services:
  server:
    image: congvan203/rychan-shop-vendure-be:latest
    ports:
      - 3000:3000
    command: ["yarn", "start:server"]
    volumes:
      - /usr/src/app
  worker:
    image: congvan203/rychan-shop-vendure-be:latest
    command: ["yarn", "start:worker"]
    volumes:
      - /usr/src/app
